version: '3'
services:
  prisma:
    container_name: ${APP_NAME}-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 4466:${PRISMA_PORT}
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql 
            migrations: true
            host: ${APP_NAME}-db
            port: 3306
            user: root
            password: prisma
    networks:
      - grademypaper_network
  db:
    container_name: ${APP_NAME}-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - grademypaper_network
volumes:
  mysql:
networks:
  grademypaper_network:
    external:
      name: grademypaper_network
