appName: MyApp
baseUrl: http://localhost
env: dev
app:
  port: 3000
prisma:
  port: 4466
  secret: myPrismaSecret
  management_secret: myPrismaManagementSecret
apollo_server:
  port: 4000
auth0:
  domain: myapp.region.auth0.com
  management_client_id: xxx
  management_client_secret: xxx
stripe:
  publishable_key: xxx
  api_secret: xxx
  allowed_webhook_events:
    - payment_intent.succeeded
  success_redirect: http://localhost:3000
  cancel_redirect: http://localhost:3000
